apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: notejam-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: notejam-prod
  minReplicas: 5
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
