apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: secrets-csi-driver
  namespace: flux-system
spec:
  chart:
    spec:
      chart: secrets-store-csi-driver
      sourceRef:
        kind: HelmRepository
        name: secret-store-csi
        namespace: flux-system
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
  values:
    syncSecret:
      enabled: true
    enableSecretRotation: true
    annotations:
         eks.amazonaws.com/role-arn:  "arn:aws:iam::003767002475:role/ascp-prod"  #TODO change as per your service account created in irsa.tf in eks module

