apiVersion: v1
clusters:
- cluster:
    server: https://7B101A7C9B2D2C60517F68820B8E6244.gr7.eu-west-1.eks.amazonaws.com
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM1ekNDQWMrZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRJeU1EUXdOREV4TlRVd05Gb1hEVE15TURRd01URXhOVFV3TkZvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTDRUCkpSbHUvZ3VpOUwybjlNWjVBN3gvYXd0OTJ3d0ZDSHkvUXNoN21IY1dEZzArNnRtMFRlcXRXWklBSE4vd0kzcUwKV2E3elpmbWlvYlZVYjZlb3kwbzhwdzRFUUQvNWMwSmdtMzROWUxGUEVXSDY3a0E0RVZLM01PYWJrOFZ1T2dmNgo0VDA5Z0gwYUsvY1V1RCtRUnRNR1BFUHVpeXlONDFyR3dtVFZMSkpaU0JQUERGci8yeEZEbW1WNUdra2Jqbnl1CjBSdGRrYVRkOEIrVWJPNGh1U3ZFckZKaVR4Z0RlUStQa2ZOSWFFUVN2c2hJemxFcGVrMDhGN2grZ001dytSdU0KdDgva1dCN1BjTnR0VXhqWXlKRmNsakNGK05TbTBnZnFzdGVGT3NFMCtQK3RmMVNJc2ZWaUZEKzdNOFo0Qk9IRApEeWhaZmNaTGpIUGo3L0Z1VlJFQ0F3RUFBYU5DTUVBd0RnWURWUjBQQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0hRWURWUjBPQkJZRUZBSW5NVnY5dFE4YUtSak1zcHl1RTdXc1VjRnhNQTBHQ1NxR1NJYjMKRFFFQkN3VUFBNElCQVFBUDZCNnptU1NnMTF6bzhXTmFnNldPS2d3RFJZVnlXbHUvaGh6R1NwSElJeUV3bVhWNwpFMHhOMHAzbndFanVMenNZVm01TGdGb3RjL0lWb1FtbmpqaW44MWIzZEdiV3NKK1o2NHpwbWtNSGhHZ3B4OHJwCmNUMlZUMnNiYlM3SjVuZElDVWR3MUxkU1RIVHhIM1BjcnlUVmtkSG1RckNqR3g5QzFxVWhjUDMzS2VWc3h5bXUKSHhSSmQxeFIxK0pHelVDL284S1dEc2hiakVlMVlnaG9lYTlxYUtYZjBCTkh5UDBrK3Rlc0ZrTjFBSWRHcDFPNAoxOEFvREhCNTF0Q1pFNFNid3U1Sy9ZRTlhUzlnV3NWaHJOSXNvN0cvV2Y0WDFSeFllNkRKdW9hcGlRZWVJWHRCCk1NOXl4cXZ0a3pKUjF5amoycy8ySFhOQVpoRzdNVXRQZWlJTAotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
  name: kubernetes
contexts:
- context:
    cluster: kubernetes
    user: aws
  name: aws
current-context: aws
kind: Config
preferences: {}
users:
- name: aws
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1alpha1
      command: aws-iam-authenticator
      args:
        - "token"
        - "-i"
        - "notejam"
        # - "-r"
        # - "role-arn"
      env:
      - name: AWS_PROFILE
        value: "sandbox"