apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
  - metrics-server.yaml
  - prometheus.yaml
  - cluster-autoscaler.yaml
  - aws-otel.yaml
  - ingress-prom.yaml