apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: ingress-class 
  namespace: flux-system
spec:
  dependsOn:
    - name: infrastructure
  interval: 1m0s
  sourceRef:
    kind: GitRepository
    name: prod-source ##TODO: change as per your source set in terraform flux module 
  path: ./ingress-Class/
  prune: true
  wait: false
  timeout: 10m
