apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageUpdateAutomation
metadata:
  name: notejam-prod-img-update
  namespace: flux-system
spec:
  interval: 30s
  sourceRef:
    name: prod-source #TODO: Change as per your source set in flux
    kind: GitRepository
    namespace: flux-system
  git:
    checkout:
      ref:
        branch: main
    commit:
      author:
        email: ahmed_qazi444@hotmail.com
        name:  build-svc
      messageTemplate: '[skip ci] Automated image update by Flux'
    push:
      branch: main
  update:
    path: ./microservices/
    strategy: Setters