apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: pgsql-secrets
  namespace: dev
spec:
  provider: aws
  parameters: 
    objects: |
      - objectName: "notejam-dev-s3-cronjob-user-ak"
        objectType: "secretsmanager"
        jmesPath:
          - path: AWS_ACCESS_KEY_ID
            objectAlias: s3-ak
      - objectName: "notejam-dev-s3-cronjob-user-sk"
        objectType: "secretsmanager"
        jmesPath:
          - path: AWS_SECRET_ACCESS_KEY
            objectAlias: s3-sk

  secretObjects:                
    - secretName: s3-backup-credentials
      type: Opaque
      data:
        #- objectName: <objectName> or <objectAlias> 
        - objectName: s3-ak
          key: AWS_ACCESS_KEY_ID
        - objectName: s3-sk
          key: AWS_SECRET_ACCESS_KEY
    
