apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: notejam-deployment-spc-k8s-secrets
  namespace: dev
spec:
  provider: aws
  parameters: 
    objects: |
      - objectName: "notejam-db-master-username-dev" #TODO: change it as per the secrets created in aws secrets manager or check terraform rds module where the secrets are created using the code 
        objectType: "secretsmanager"
        jmesPath:
          - path: POSTGRES_USER
            objectAlias: dbusername
      - objectName: "notejam-db-master-password-dev" #TODO: change it as per the secrets created in aws secrets manager or check terraform rds module where the secrets are created using the code 
        objectType: "secretsmanager"
        jmesPath:
          - path: POSTGRES_PASS
            objectAlias: dbpass
      - objectName: "notejam-db-host-dev" #TODO: change it as per the secrets created in aws secrets manager or check terraform rds module where the secrets are created using the code 
        objectType: "secretsmanager"
        jmesPath:
          - path: POSTGRES_URL
            objectAlias: dbhost
      - objectName: "notejam-db-name-dev" #TODO: change it as per the secrets created in aws secrets manager or check terraform rds module where the secrets are created using the code 
        objectType: "secretsmanager"
        jmesPath:
          - path: POSTGRES_DB
            objectAlias: dbname

          

    
  # Create k8s secret. It requires volume mount first in the pod and then sync.
  secretObjects:                
    - secretName: db-credentials
      type: Opaque
      data:
        #- objectName: <objectName> or <objectAlias> 
        - objectName: dbusername
          key: POSTGRES_USER
        - objectName: dbpass
          key: POSTGRES_PASS
        - objectName: dbhost
          key:  POSTGRES_URL
        - objectName: dbname
          key: POSTGRES_DB
    
