apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: secrets-store-provider-aws
  namespace: dev
spec:
  chart:
    spec:
      chart: secrets-store-csi-driver-provider-aws
      sourceRef:
        kind: HelmRepository
        name: secrets-manager
        namespace: flux-system
      version: "0.4.0"
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
  values:
      serviceAccount:
        create: true
        name: ascp-csi-secrets-store-provider-aws
      additionalAnnotations:
       eks.amazonaws.com/role-arn:  "arn:aws:iam::003767002475:role/ascp-dev" #TODO: created by irsa

     
    