---
name: Build and Push Notejam-Flask Image to AWS ECR
on:
  push:
    branches: [ main ]
jobs:
  build-and-push:
    name: Build and Push to ECR
    runs-on: ubuntu-latest
    permissions:
     id-token: write
     contents: read

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@master
      with:
        role-to-assume: arn:aws:iam::003767002475:role/github-oidc
        role-duration-seconds: 900 
        aws-region: eu-west-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
          
    - name: Build, Tag, and Push the Image to Amazon ECR
      id: build-image
      uses: docker/build-push-action@v2
      with: 
        registry: ${{steps.login-ecr.outputs.registry}}
        repository: ${{ steps.login-ecr.outputs.registry }}/${{ secrets.REGISTRY }}
        file: notejam-flask/Dockerfile.prod
        platforms: linux/amd64
        push: ${{ github.event_name != 'pull_request' }}
        add_git_labels: true
        tags: |
           repo:${{ github.sha }}
          

    