---
name: Build and Push Notejam-Flask Image to AWS ECR
on:
  push:
    branches: [ main ]
    #paths:
    #- notejam-flask/**
  pull_request:
    paths:
    - notejam-flask/**
jobs:
  build-and-push:
    name: Build and Push to ECR
    runs-on: ubuntu-latest
    permissions:
     id-token: write
     contents: read

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@master
      with:
        role-to-assume: arn:aws:iam::003767002475:role/github-oidc
        role-duration-seconds: 900 
        aws-region: eu-west-1
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push image to Amazon ECR
      id: build-image
      env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ secrets.REGISTRY }}
          IMAGE_TAG: ${{ steps.login-ecr.outputs.registry }}/${{ secrets.REGISTRY }}:${{ steps.config.outputs.version }}
      run: |
          buildah bud -f - --squash --format=docker --pull -t $IMAGE_TAG . 
          buildah push $IMAGE_TAG
          echo "::set-output name=image::$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"

    - name: Prepare configs
      id: config
      shell: bash
      run: |
        GITHUB_SHA='${{ github.sha }}'
        GITHUB_REF='${{ env.GITHUB_REF_SLUG_URL }}'
        VERSION="$(date +'%Y.%m.%d').${GITHUB_REF}-${GITHUB_SHA::8}-${{ github.run_id }}"
        echo "Setting version parameter to ${VERSION}"
        echo "::set-output name=version::${VERSION}"
    outputs:
        version: ${{ steps.config.outputs.version }}



    